name: CD - Deploy to Render

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  publish:
    name: Build & Push Docker image to GHCR
    runs-on: ubuntu-latest
    outputs:
      image_name: ${{ steps.meta.outputs.image_name }}

    steps:
      - name: Checkout commit
        uses: actions/checkout@v4

      - name: Set image meta (tag by commit SHA)
        id: meta
        run: |
          REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')
          echo "repo_lc=${REPO_LC}" >> "$GITHUB_OUTPUT"
          echo "image_name=ghcr.io/${REPO_LC}:${{ github.sha }}" >> "$GITHUB_OUTPUT"


      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            ${{ steps.meta.outputs.image_name }}
            ghcr.io/${{ steps.meta.outputs.repo_lc }}:main

  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    needs: publish
    if: always() && needs.publish.result == 'success'
    steps:
      - name: Trigger Render deploy
        run: |
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK"
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}